### ISSUE TITLE
Down Sample Rate

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#12]
I was wondering how changing the down sample rate changes other aspects of the stimulus.  I noticed that lowering it causes the stimulus to move more slowly despite not changing the speed of the stimulus.  Is there a way to calculate how to change other parameters to compensate for an adjusted down sample rate?

**Comment by zhuangjun1981** [comment]
I have got the similar issues from other users. If your down sample rate is too low, you are asking the system to display high resolution images. To some extent, your system will fail and have lots of lagged frames and the display will appear much slower. Pay attention to the print out of the console after each display to see if your frame rate is what you are expecting. If not, try increase the down sample rate. I usually use 5, since my system cannot keep up with 1 or 2.

**Comment by triplem0814** [comment]
So the expected versus actual time should give me a good sense of how well it is working?

**Comment by zhuangjun1981** [comment]
Yes.

**Comment by triplem0814** [comment]
Thank you.
