### ISSUE TITLE
Analysis: initialize class with raw images?

### ISSUE THREAD

**Issue by hillierdani** [zhuangjun1981/retinotopic_mapping#7]
Hi,
In you very nice and clean code I miss one bit: given the raw series of camera images how should I initialize the analysis class? In your code you seem to import already preprocessed data.
Thanks!

**Comment by zhuangjun1981** [comment]
This is right. Because of the various hardware and software that people are using for acquire images, there is no universal way to preprocess data. I assume all the preprocessing will converge into an intermediate stage that is universal. That is an azimuth map and an altitude map of cortex (ideally also a vasculature map), all in same size. My jupyter notebook example start from there, calculating the visual sign map and segmenting the sign map into several patch (putative visual areas).

**Comment by zhuangjun1981** [comment]
I have updated the example notebook to describe the preprocessing steps to generate altitude map and azimuth map.
